language: python
sudo: required
dist: trusty
python:
  - 2.7
  - 3.4
install:
 - pip install .
 - pip install -r requirements-dev.txt
script:
 - pwd
 - ls
 - PYTHONPATH="." python -m unittest discover
