language: python
sudo: required
dist: trusty
python:
  - 2.7
  - 3.4
install:
 - pip install .
 - pip install -r requirements-dev.txt
script:
 - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python -m unittest discover; fi
 - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then python -m unittest discover; fi